---
# tasks file for rbabu.wordpress


# Copy the wordpress zip file 
- name: "Starting wordpress deployment, copying wordpress zip into tmp"
  copy: 
    src: wordpress.zip 
    dest: /tmp/wordpress.zip 

- name: "Install required tools 'unzip'"
  apt: 
    name: unzip 
    state: present 

# Unziping wordpress
- name: "Unzip WordPress"
  unarchive: 
    src: /tmp/wordpress.zip 
    dest: /tmp 
    copy: no 
    creates: /tmp/wordpress/wp-settings.php

- name: "Create project folder"
  file: 
    dest: /var/www/{{wp_domain}} 
    state: directory

# Display name and url of wordpress website
#- name: "Your website name is "


- name: "Copy WordPress files"
  command: cp -a /tmp/wordpress/. /var/www/{{wp_domain}} creates=/var/www/{{wp_domain}}/wp-settings.php

- name: "Copy the wp-config.php to wordpress document root"
  copy :
    src: wp-config.php
    dest: /var/www/{{wp_domain}}

# Create wordpress db in MySQL database
- name: "Create WordPress MySQL database"
  mysql_db: 
    name: "{{database_name}}"
    state: present

# Creating wordpress users in MySQL database
- name: Create WordPress MySQL user
  mysql_user: 
    name: "{{database_user}}"
    host: localhost 
    password: "{{database_password}}" 
    priv: "{{database_name}}.*:ALL"